_BASE_: "../Base-CenterMask-VoVNet-sor.yaml"
MODEL:
  WEIGHTS: "pretrained/centermask2-V-39-eSE-FPN-ms-3x.pth"
  VOVNET:
    CONV_BODY : "V-39-eSE"
  DET_WEIGHTS: 0.0


  SOR:
    NAME: "SinglePredictorWithPos"
    CONV_DIM: 256
    NUM_CONV: 4
    DENSE_DIM: 1024
    OBJ_DIM: 1024
    TRANSFORMER:
      D_MODEL: 1024
      N_HEAD: 4
      LAYERS: 4
      USE_POS: True




SOLVER:
  BASE_LR: 1e-4
  STEPS: (42000, 50000)
  MAX_ITER: 54000
OUTPUT_DIR: "output/sor/exp/only_pos/"
TEST:
  EVAL_PERIOD: 1000
